# Numpy | Machine Learning | Coding Ninjas

In [10]:
import numpy as np
import math as m

## Creating a Numpy Array

In [2]:
l = [1,2,3,4] # This is a List
np.array(l) # Converting List into Numpy Array

array([1, 2, 3, 4])

#### If we add string elements in a list then while creating numpy array it will convert every element into string as we have to follow the same datatype for every element in Numpy Arrays.

In [3]:
m = [1,2,"a","4"] # This is a List
np.array(m) # Converting List into Numpy Array

array(['1', '2', 'a', '4'], dtype='<U11')

## Array Helper Functions in Numpy

In [4]:
# Single Dimentional Arrays

aa = np.zeros(10)
print(aa)
print(aa.dtype)
bb = np.ones(10)
print(bb)
print(aa.dtype)
cc = np.zeros(10, int)
print(cc)
print(aa.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
[0 0 0 0 0 0 0 0 0 0]
float64


#### For creating a Multi Dimentional Arrays we need to pass the first argument in brackets and in this if we want to make 2-D array the 2 arguments, if 3-D then three arguments and so on.

In [5]:
# Multi Dimentional Arrays

# 2-D
dd = np.zeros((3,5))
print(dd)
ee = np.zeros((3,5),int)
print(ee)

# 3-D
ff = np.zeros((3,5,3))
print(ff)
gg = np.zeros((3,5,3),int)
print(gg)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


## Shape Function

In [6]:
# Printing the Shape of all arrays created.
# Shape Function tells the Size

print(aa.shape)
print(bb.shape)
print(cc.shape)
print(dd.shape)
print(ee.shape)
print(ff.shape)
print(gg.shape)

(10,)
(10,)
(10,)
(3, 5)
(3, 5)
(3, 5, 3)
(3, 5, 3)


## Create 2-D Numpy Array Manually

In [7]:
hh = np.array(([1,2,3],[4,5,6],[7,8,9]))
print("Array:")
print(hh)
print("Shape:")
print(hh.shape)
print("Data Type:")
print(hh.dtype)

## Accessing the Elements
print("hh[0] is:")
print(hh[0])
print("hh[0][1] is:")
print(hh[0][1])

## Need only Columns Part
print("All Rows + First Columns Elements =")
print(hh[:,0])
print("0, 1 Rows + Second Columns Elements =")
print(hh[0:2,1:])
print("0, 1 Rows + 2, 3 Columns Elements =")
print(hh[0:2,1:])

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:
(3, 3)
Data Type:
int32
hh[0] is:
[1 2 3]
hh[0][1] is:
2
All Rows + First Columns Elements =
[1 4 7]
0, 1 Rows + Second Columns Elements =
[[2 3]
 [5 6]]
0, 1 Rows + 2, 3 Columns Elements =
[[2 3]
 [5 6]]


## Numpy Operations

In [8]:
ii = np.array([1,2,3])
jj = np.array([5,6,7])
print("First Array:",ii)
print("Second Array:",jj)
print("Add 2 to Each Element of First Array:",ii+2)
print("Add First and Second Array:",ii+jj)
# Adding two arrays the arrays must be of same size
print("Multiply 2 to Each Element of First Array:",ii*2)
print("Power 2 to Each Element of First Array:",ii**2)

print("Mean of First Array:",ii.mean())
print("Sum of First Array:",ii.sum())

First Array: [1 2 3]
Second Array: [5 6 7]
Add 2 to Each Element of First Array: [3 4 5]
Add First and Second Array: [ 6  8 10]
Multiply 2 to Each Element of First Array: [2 4 6]
Power 2 to Each Element of First Array: [1 4 9]
Mean of First Array: 2.0
Sum of First Array: 6


## Square Distance in a N-N Array

#### Suppose we have a N-D Array and we are given to points in that Array where on those points we need to find the "SQUARE DISTANCE"

#### First Point in that Array is [1,2,3]
##### Second Point in that Array is [5,6,7]

#### Formula of Square Distance in these to points will be: 
#### Square Root((1-5)^2 + (2-6)^2 + (3-7)^2)

#### Finding this with the help of Numpy Array Operations:

In [11]:
squareDistance = ((ii - jj) ** 2).sum()
squareDistance = m.sqrt(squareDistance)
print(squareDistance)

6.928203230275509


## Calculate Sum(All Array Elements - Array Mean)^2

In [12]:
kk = np.array([1,3,5,6])
print(((kk - kk.mean()) ** 2).sum())

14.75


## Dot Product in 2-D Arrays

In [13]:
ll = np.array(([1,2],[3,4]))
mm = np.array(([10,20],[30,40]))
print(ll.dot(mm))

[[ 70 100]
 [150 220]]
