# Combined Cycle Power Plant | Gradient Descent | Machine Learning

In [1]:
import numpy as np
import pandas as pd

## Importing the Train and Test Data

In [2]:
data_train = np.genfromtxt("train_data.csv", delimiter = ",")
data_test = np.genfromtxt("test_data.csv", delimiter = ",")
data_train, data_test

(array([[   8.58,   38.38, 1021.03,   84.37,  482.26],
        [  21.79,   58.2 , 1017.21,   66.74,  446.94],
        [  16.64,   48.92, 1011.55,   78.76,  452.56],
        ...,
        [  29.8 ,   69.34, 1009.36,   64.74,  437.65],
        [  16.37,   54.3 , 1017.94,   63.63,  459.97],
        [  30.11,   62.04, 1010.69,   47.96,  444.42]]),
 array([[  11.95,   42.03, 1017.58,   90.89],
        [  12.07,   38.25, 1012.67,   81.66],
        [  26.91,   74.99, 1005.64,   78.98],
        ...,
        [  24.32,   66.25, 1009.09,   91.89],
        [  23.49,   42.8 , 1013.96,   65.31],
        [  21.76,   60.27, 1018.96,   85.06]]))

## Converting Train Data to DataFrame

In [3]:
df_train = pd.DataFrame(data_train)
df_train

0      1        2      3       4
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
...     ...    ...      ...    ...     ...
7171   9.32  37.73  1022.14  79.49  477.91
7172  11.20  41.38  1021.65  61.89  476.87
7173  29.80  69.34  1009.36  64.74  437.65
7174  16.37  54.30  1017.94  63.63  459.97
7175  30.11  62.04  1010.69  47.96  444.42

[7176 rows x 5 columns]

## Separating Input and Output of Train Data

In [4]:
df_input = df_train.iloc[:,0:4]
df_output = df_train.iloc[:,4]
df_input, df_output

(          0      1        2      3
 0      8.58  38.38  1021.03  84.37
 1     21.79  58.20  1017.21  66.74
 2     16.64  48.92  1011.55  78.76
 3     31.38  71.32  1009.17  60.42
 4      9.20  40.03  1017.05  92.46
 ...     ...    ...      ...    ...
 7171   9.32  37.73  1022.14  79.49
 7172  11.20  41.38  1021.65  61.89
 7173  29.80  69.34  1009.36  64.74
 7174  16.37  54.30  1017.94  63.63
 7175  30.11  62.04  1010.69  47.96
 
 [7176 rows x 4 columns],
 0       482.26
 1       446.94
 2       452.56
 3       433.44
 4       480.38
          ...  
 7171    477.91
 7172    476.87
 7173    437.65
 7174    459.97
 7175    444.42
 Name: 4, Length: 7176, dtype: float64)

## Applying Combinations on Data

In [5]:
check = []
temp = None
i = 1
df_temp_input = pd.DataFrame(temp)
for i in df_input:
    check = check + [i]
    for j in df_input:
        if j in check:
            continue
        else:
            name = df_input.shape[1] + i
            i = i + 1
            check = check + [name]
            df_temp_input[name] = df_input[i]*df_input[j]

for i in df_temp_input:
    df_input[i] = df_temp_input[i]
df_input

0      1        2      3          4             5          6
0      8.58  38.38  1021.03  84.37  1473.0244  1.042502e+06  7118.2969
1     21.79  58.20  1017.21  66.74  3387.2400  1.034716e+06  4454.2276
2     16.64  48.92  1011.55  78.76  2393.1664  1.023233e+06  6203.1376
3     31.38  71.32  1009.17  60.42  5086.5424  1.018424e+06  3650.5764
4      9.20  40.03  1017.05  92.46  1602.4009  1.034391e+06  8548.8516
...     ...    ...      ...    ...        ...           ...        ...
7171   9.32  37.73  1022.14  79.49  1423.5529  1.044770e+06  6318.6601
7172  11.20  41.38  1021.65  61.89  1712.3044  1.043769e+06  3830.3721
7173  29.80  69.34  1009.36  64.74  4808.0356  1.018808e+06  4191.2676
7174  16.37  54.30  1017.94  63.63  2948.4900  1.036202e+06  4048.7769
7175  30.11  62.04  1010.69  47.96  3848.9616  1.021494e+06  2300.1616

[7176 rows x 7 columns]

In [6]:
df_test = pd.DataFrame(data_test)
check = []
temp = None
i = 1
df_test_input = pd.DataFrame(temp)
for i in df_test:
    check = check + [i]
    for j in df_test:
        if j in check:
            continue
        else:
            name = df_test.shape[1] + i
            i = i + 1
            check = check + [name]
            df_test_input[name] = df_test[i]*df_test[j]

for i in df_test_input:
    df_test[i] = df_test_input[i]
df_test


0      1        2      3          4             5          6
0     11.95  42.03  1017.58  90.89  1766.5209  1.035469e+06  8260.9921
1     12.07  38.25  1012.67  81.66  1463.0625  1.025501e+06  6668.3556
2     26.91  74.99  1005.64  78.98  5623.5001  1.011312e+06  6237.8404
3     20.58  39.53  1005.68  62.09  1562.6209  1.011392e+06  3855.1681
4     16.78  37.20  1011.97  68.94  1383.8400  1.024083e+06  4752.7236
...     ...    ...      ...    ...        ...           ...        ...
2387  29.49  69.71  1009.34  56.35  4859.4841  1.018767e+06  3175.3225
2388  27.69  65.34  1014.31  46.59  4269.3156  1.028825e+06  2170.6281
2389  24.32  66.25  1009.09  91.89  4389.0625  1.018263e+06  8443.7721
2390  23.49  42.80  1013.96  65.31  1831.8400  1.028115e+06  4265.3961
2391  21.76  60.27  1018.96  85.06  3632.4729  1.038279e+06  7235.2036

[2392 rows x 7 columns]

## Converting the Data to Numpy Array

In [7]:
X_train = df_input.to_numpy()
Y_train = df_output.to_numpy()
X_test = df_test.to_numpy()
X_train,Y_train,X_test

(array([[8.58000000e+00, 3.83800000e+01, 1.02103000e+03, ...,
         1.47302440e+03, 1.04250226e+06, 7.11829690e+03],
        [2.17900000e+01, 5.82000000e+01, 1.01721000e+03, ...,
         3.38724000e+03, 1.03471618e+06, 4.45422760e+03],
        [1.66400000e+01, 4.89200000e+01, 1.01155000e+03, ...,
         2.39316640e+03, 1.02323340e+06, 6.20313760e+03],
        ...,
        [2.98000000e+01, 6.93400000e+01, 1.00936000e+03, ...,
         4.80803560e+03, 1.01880761e+06, 4.19126760e+03],
        [1.63700000e+01, 5.43000000e+01, 1.01794000e+03, ...,
         2.94849000e+03, 1.03620184e+06, 4.04877690e+03],
        [3.01100000e+01, 6.20400000e+01, 1.01069000e+03, ...,
         3.84896160e+03, 1.02149428e+06, 2.30016160e+03]]),
 array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42]),
 array([[1.19500000e+01, 4.20300000e+01, 1.01758000e+03, ...,
         1.76652090e+03, 1.03546906e+06, 8.26099210e+03],
        [1.20700000e+01, 3.82500000e+01, 1.01267000e+03, ...,
         1.46306250e

## Append 1 to Last

In [8]:
X_train = np.append(X_train, np.ones(X_train.shape[0]).reshape(-1, 1), axis=1)
X_test = np.append(data_test, np.ones(data_test.shape[0]).reshape(-1, 1), axis=1)
X_train,X_test

(array([[8.58000000e+00, 3.83800000e+01, 1.02103000e+03, ...,
         1.04250226e+06, 7.11829690e+03, 1.00000000e+00],
        [2.17900000e+01, 5.82000000e+01, 1.01721000e+03, ...,
         1.03471618e+06, 4.45422760e+03, 1.00000000e+00],
        [1.66400000e+01, 4.89200000e+01, 1.01155000e+03, ...,
         1.02323340e+06, 6.20313760e+03, 1.00000000e+00],
        ...,
        [2.98000000e+01, 6.93400000e+01, 1.00936000e+03, ...,
         1.01880761e+06, 4.19126760e+03, 1.00000000e+00],
        [1.63700000e+01, 5.43000000e+01, 1.01794000e+03, ...,
         1.03620184e+06, 4.04877690e+03, 1.00000000e+00],
        [3.01100000e+01, 6.20400000e+01, 1.01069000e+03, ...,
         1.02149428e+06, 2.30016160e+03, 1.00000000e+00]]),
 array([[1.19500e+01, 4.20300e+01, 1.01758e+03, 9.08900e+01, 1.00000e+00],
        [1.20700e+01, 3.82500e+01, 1.01267e+03, 8.16600e+01, 1.00000e+00],
        [2.69100e+01, 7.49900e+01, 1.00564e+03, 7.89800e+01, 1.00000e+00],
        ...,
        [2.43200e+01, 6.625

## Gradient Descent Algorithm

In [18]:
def gradient_descent():
    learning_rate = 0.0000000000001
    iterations = 1000
    m = find_M(X_train,Y_train,learning_rate,iterations)
    return m

def find_M(X_train,Y_train,learning_rate,iterations):
    m = np.array([0 for i in range(len(X_train[0]))])
    for i in range(iterations):
        m = step_gradient(X_train,Y_train,learning_rate,m)
        print("Cost: ",cost(X_train, Y_train,m))
    return m

def step_gradient(X_train,Y_train, learning_rate, m):
    M = X_train.shape[0]
    N = X_train.shape[1]
    m_slope = np.zeros(N)
    for i in range(M):
        x = X_train[i]
        y = Y_train[i]
        for j in range(N):
            m_slope[j] += (-2/M)*(y - (m*x).sum())*(x[j])
    new_m = m - learning_rate * m_slope
    return new_m

def cost(X_train, y_train, m):
    result = 0
    N = X_train.shape[0]
    for i in range(N):
        x = X_train[i]
        y = Y_train[i]
        result += (1/N)*((y-((m*x).sum()))**2)
    return result

m = gradient_descent()
m

Cost:  128864.32373053623
Cost:  80331.59050707312
Cost:  50109.41983025464
Cost:  31289.552473398217
Cost:  19570.096186340048
Cost:  12272.188418505113
Cost:  7727.655225137123
Cost:  4897.695899806686
Cost:  3135.431313949481
Cost:  2038.0386697156425
Cost:  1354.6732585617044
Cost:  929.1297511465406
Cost:  664.1363929402046
Cost:  499.1203835828142
Cost:  396.3619948637445
Cost:  332.3725010211054
Cost:  292.5250671308336
Cost:  267.7113106410418
Cost:  252.25928453500802
Cost:  242.6369695132336
Cost:  236.6449161987713
Cost:  232.91348950427286
Cost:  230.58979402230696
Cost:  229.14271706253604
Cost:  228.24152558620565
Cost:  227.68026642196077
Cost:  227.33068897544953
Cost:  227.11292938809294
Cost:  226.97725505678085
Cost:  226.8926966312226
Cost:  226.83996896248985
Cost:  226.80706285550525
Cost:  226.78649997722474
Cost:  226.7736234405927
Cost:  226.76553332167
Cost:  226.7604237877676
Cost:  226.75717031570298
Cost:  226.7550726454815
Cost:  226.753694713121
Cost:  22

Cost:  226.69835982590624
Cost:  226.69816992120218
Cost:  226.69798001677373
Cost:  226.69779011262204
Cost:  226.69760020874475
Cost:  226.69741030514257
Cost:  226.69722040181685
Cost:  226.6970304987661
Cost:  226.69684059599072
Cost:  226.69665069349116
Cost:  226.6964607912667
Cost:  226.69627088931796
Cost:  226.69608098764553
Cost:  226.69589108624655
Cost:  226.69570118512507
Cost:  226.69551128427642
Cost:  226.69532138370624
Cost:  226.69513148340997
Cost:  226.6949415833896
Cost:  226.69475168364383
Cost:  226.69456178417553
Cost:  226.69437188498085
Cost:  226.69418198606178
Cost:  226.693992087418
Cost:  226.69380218905036
Cost:  226.69361229095875
Cost:  226.69342239314145
Cost:  226.6932324956
Cost:  226.69304259833444
Cost:  226.69285270134378
Cost:  226.69266280462926
Cost:  226.69247290818905
Cost:  226.69228301202588
Cost:  226.69209311613696
Cost:  226.69190322052373
Cost:  226.6917133251857
Cost:  226.6915234301222
Cost:  226.6913335353352
Cost:  226.6911436408254

Cost:  226.63760437827946
Cost:  226.63741456170263
Cost:  226.63722474540143
Cost:  226.6370349293759
Cost:  226.63684511362547
Cost:  226.63665529815015
Cost:  226.63646548294975
Cost:  226.63627566802478
Cost:  226.63608585337633
Cost:  226.63589603900206
Cost:  226.6357062249038
Cost:  226.6355164110803
Cost:  226.6353265975319
Cost:  226.63513678425966
Cost:  226.63494697126336
Cost:  226.63475715853986
Cost:  226.63456734609412
Cost:  226.63437753392284
Cost:  226.63418772202547
Cost:  226.63399791040501
Cost:  226.63380809905934
Cost:  226.6336182879898
Cost:  226.6334284771954
Cost:  226.63323866667596
Cost:  226.63304885643242
Cost:  226.63285904646347
Cost:  226.63266923676932
Cost:  226.6324794273502
Cost:  226.63228961820766
Cost:  226.63209980934008
Cost:  226.63191000074775
Cost:  226.63172019243112
Cost:  226.6315303843905
Cost:  226.63134057662202
Cost:  226.63115076913212
Cost:  226.63096096191524
Cost:  226.63077115497575
Cost:  226.63058134831059
Cost:  226.630391541

Cost:  226.57706685266243
Cost:  226.57687712389003
Cost:  226.57668739539469
Cost:  226.5764976671748
Cost:  226.57630793922831
Cost:  226.57611821155714
Cost:  226.57592848416323
Cost:  226.57573875704242
Cost:  226.57554903019744
Cost:  226.5753593036282
Cost:  226.57516957733324
Cost:  226.57497985131533
Cost:  226.57479012557144
Cost:  226.57460040010207
Cost:  226.57441067490763
Cost:  226.57422094998952
Cost:  226.57403122534623
Cost:  226.57384150097786
Cost:  226.57365177688465
Cost:  226.57346205306703
Cost:  226.57327232952488
Cost:  226.57308260625663
Cost:  226.57289288326402
Cost:  226.57270316054786
Cost:  226.57251343810475
Cost:  226.57232371593787
Cost:  226.57213399404574
Cost:  226.57194427243076
Cost:  226.57175455108825
Cost:  226.571564830023
Cost:  226.57137510923036
Cost:  226.57118538871495
Cost:  226.57099566847558
Cost:  226.570805948509
Cost:  226.57061622881855
Cost:  226.57042650940355
Cost:  226.57023679026372
Cost:  226.57004707139913
Cost:  226.5698573

array([-1.19304981e-08, -9.36599170e-09,  4.32520930e-07,  4.90553553e-08,
       -2.21675626e-06,  4.42617640e-04,  4.92780647e-06,  4.22647870e-10])

## Prediction on Test Data

In [32]:
def predict(X_test,m):
    N = X_test.shape[0]
    Y_pred = np.zeros(N)
    for i in range(N):
        Y_pred[i] = (m*X_test[i]).sum()
    return Y_pred
Y_pred = predict(X_test,m)

In [34]:
Y_pred

array([471.04327105, 469.45337545, 435.07043127, ..., 445.84477681,
       459.05075807, 454.40345147])

In [36]:
np.savetxt('E:/MACHINE LEARNING/Milestone 2/Module 4 - Projects Gradient Descent/Project Combined Cycle Power Plant/pred.csv', Y_pred)