# Boston Dataset

In [1]:
from sklearn import datasets

## Importing Boston Data

In [2]:
boston = datasets.load_boston()
print(boston)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

C:\Users\hp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e

## Analysing the Data

In [3]:
data = boston.data
target = boston.target
print(data)
print(target)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

## Converting Data to DataFrame

In [4]:
import pandas as pd
boston_dataframe = pd.DataFrame(data)
boston_dataframe

0     1      2    3      4      5     6       7    8      9     10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  
0    396.90  4.98  
1    396.90  9.14  
2    392.83  4.03  
3    394.63  2.94  
4    396.90  5.33  
..      ...   ...  
501  391.99  9.67  
502  396.90  9.08  
503  396.90  5.64  
504  393.45  6.48  
505  396.90  7.88  

[506 rows x 13 columns]

## Adding Heading to DataFrame

In [5]:
boston_dataframe.columns = boston.feature_names
temp = None
temp_dataframe = pd.DataFrame(temp)
check = []
for i in boston_dataframe:
    name = i + '_' + i
    check = check + [name]
    boston_dataframe[i + '_' + i] = boston_dataframe[i] ** 2
    
for i in boston_dataframe:
    check = check + [i]
    for j in boston_dataframe:
        if j in check:
            continue
        else:
            temp_dataframe[i + '_' + j] = boston_dataframe[i]*boston_dataframe[j]
temp_dataframe

CRIM_ZN  CRIM_INDUS  CRIM_CHAS  CRIM_NOX   CRIM_RM  CRIM_AGE  CRIM_DIS  \
0    0.11376    0.014599        0.0  0.003400  0.041554  0.412064  0.025849   
1    0.00000    0.193082        0.0  0.012808  0.175358  2.154759  0.135652   
2    0.00000    0.192940        0.0  0.012799  0.196079  1.667419  0.135552   
3    0.00000    0.070567        0.0  0.014825  0.226525  1.482546  0.196233   
4    0.00000    0.150529        0.0  0.031625  0.493500  3.742510  0.418595   
..       ...         ...        ...       ...       ...       ...       ...   
501  0.00000    0.747176        0.0  0.035887  0.412920  4.327733  0.155235   
502  0.00000    0.540071        0.0  0.025940  0.277052  3.472209  0.103555   
503  0.00000    0.724867        0.0  0.034815  0.423862  5.529160  0.131697   
504  0.00000    1.307409        0.0  0.062795  0.744554  9.786387  0.261800   
505  0.00000    0.565601        0.0  0.027166  0.285882  3.830728  0.118762   

     CRIM_RAD  CRIM_TAX  CRIM_PTRATIO  ...  RAD_TAX  RAD_PTRATIO    RAD_B  \
0     0.00632   1.87072      0.096696  ...    296.0         15.3   396.90   
1     0.05462   6.60902      0.486118  ...    484.0         35.6   793.80   
2     0.05458   6.60418      0.485762  ...    484.0         35.6   785.66   
3     0.09711   7.18614      0.605319  ...    666.0         56.1  1183.89   
4     0.20715  15.32910      1.291235  ...    666.0         56.1  1190.70   
..        ...       ...           ...  ...      ...          ...      ...   
501   0.06263  17.09799      1.315230  ...    273.0         21.0   391.99   
502   0.04527  12.35871      0.950670  ...    273.0         21.0   396.90   
503   0.06076  16.58748      1.275960  ...    273.0         21.0   396.90   
504   0.10959  29.91807      2.301390  ...    273.0         21.0   393.45   
505   0.04741  12.94293      0.995610  ...    273.0         21.0   396.90   

     RAD_LSTAT  TAX_PTRATIO      TAX_B  TAX_LSTAT  PTRATIO_B  PTRATIO_LSTAT  \
0         4.98       4528.8  117482.40    1474.08   6072.570         76.194   
1        18.28       4307.6   96049.80    2211.88   7064.820        162.692   
2         8.06       4307.6   95064.86     975.26   6992.374         71.734   
3         8.82       4151.4   87607.86     652.68   7379.581         54.978   
4        15.99       4151.4   88111.80    1183.26   7422.030         99.671   
..         ...          ...        ...        ...        ...            ...   
501       9.67       5733.0  107013.27    2639.91   8231.790        203.070   
502       9.08       5733.0  108353.70    2478.84   8334.900        190.680   
503       5.64       5733.0  108353.70    1539.72   8334.900        118.440   
504       6.48       5733.0  107411.85    1769.04   8262.450        136.080   
505       7.88       5733.0  108353.70    2151.24   8334.900        165.480   

       B_LSTAT  
0    1976.5620  
1    3627.6660  
2    1583.1049  
3    1160.2122  
4    2115.4770  
..         ...  
501  3790.5433  
502  3603.8520  
503  2238.5160  
504  2549.5560  
505  3127.5720  

[506 rows x 78 columns]

## Combining two Data Frames

In [6]:
boston_dataframe

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  ...  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0  ...   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0  ...   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0  ...   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0  ...   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0  ...   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0  ...   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0  ...   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0  ...   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0  ...   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0  ...   

     CHAS_CHAS   NOX_NOX      RM_RM  AGE_AGE    DIS_DIS  RAD_RAD  TAX_TAX  \
0          0.0  0.289444  43.230625  4251.04  16.728100      1.0  87616.0   
1          0.0  0.219961  41.229241  6225.21  24.672082      4.0  58564.0   
2          0.0  0.219961  51.624225  3733.21  24.672082      4.0  58564.0   
3          0.0  0.209764  48.972004  2097.64  36.750269      9.0  49284.0   
4          0.0  0.209764  51.079609  2937.64  36.750269      9.0  49284.0   
..         ...       ...        ...      ...        ...      ...      ...   
501        0.0  0.328329  43.467649  4774.81   6.143458      1.0  74529.0   
502        0.0  0.328329  37.454400  5882.89   5.232656      1.0  74529.0   
503        0.0  0.328329  48.664576  8281.00   4.698056      1.0  74529.0   
504        0.0  0.328329  46.158436  7974.49   5.706843      1.0  74529.0   
505        0.0  0.328329  36.360900  6528.64   6.275025      1.0  74529.0   

     PTRATIO_PTRATIO          B_B  LSTAT_LSTAT  
0             234.09  157529.6100      24.8004  
1             316.84  157529.6100      83.5396  
2             316.84  154315.4089      16.2409  
3             349.69  155732.8369       8.6436  
4             349.69  157529.6100      28.4089  
..               ...          ...          ...  
501           441.00  153656.1601      93.5089  
502           441.00  157529.6100      82.4464  
503           441.00  157529.6100      31.8096  
504           441.00  154802.9025      41.9904  
505           441.00  157529.6100      62.0944  

[506 rows x 26 columns]

In [7]:
for i in temp_dataframe:
    boston_dataframe[i] = temp_dataframe[i]

In [8]:
boston_dataframe

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  ...  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0  ...   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0  ...   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0  ...   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0  ...   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0  ...   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0  ...   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0  ...   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0  ...   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0  ...   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0  ...   

     RAD_TAX  RAD_PTRATIO    RAD_B  RAD_LSTAT  TAX_PTRATIO      TAX_B  \
0      296.0         15.3   396.90       4.98       4528.8  117482.40   
1      484.0         35.6   793.80      18.28       4307.6   96049.80   
2      484.0         35.6   785.66       8.06       4307.6   95064.86   
3      666.0         56.1  1183.89       8.82       4151.4   87607.86   
4      666.0         56.1  1190.70      15.99       4151.4   88111.80   
..       ...          ...      ...        ...          ...        ...   
501    273.0         21.0   391.99       9.67       5733.0  107013.27   
502    273.0         21.0   396.90       9.08       5733.0  108353.70   
503    273.0         21.0   396.90       5.64       5733.0  108353.70   
504    273.0         21.0   393.45       6.48       5733.0  107411.85   
505    273.0         21.0   396.90       7.88       5733.0  108353.70   

     TAX_LSTAT  PTRATIO_B  PTRATIO_LSTAT    B_LSTAT  
0      1474.08   6072.570         76.194  1976.5620  
1      2211.88   7064.820        162.692  3627.6660  
2       975.26   6992.374         71.734  1583.1049  
3       652.68   7379.581         54.978  1160.2122  
4      1183.26   7422.030         99.671  2115.4770  
..         ...        ...            ...        ...  
501    2639.91   8231.790        203.070  3790.5433  
502    2478.84   8334.900        190.680  3603.8520  
503    1539.72   8334.900        118.440  2238.5160  
504    1769.04   8262.450        136.080  2549.5560  
505    2151.24   8334.900        165.480  3127.5720  

[506 rows x 104 columns]

In [9]:
X2 = boston_dataframe.values
print(X2)
boston_dataframe.describe()

[[6.3200000e-03 1.8000000e+01 2.3100000e+00 ... 6.0725700e+03
  7.6194000e+01 1.9765620e+03]
 [2.7310000e-02 0.0000000e+00 7.0700000e+00 ... 7.0648200e+03
  1.6269200e+02 3.6276660e+03]
 [2.7290000e-02 0.0000000e+00 7.0700000e+00 ... 6.9923740e+03
  7.1734000e+01 1.5831049e+03]
 ...
 [6.0760000e-02 0.0000000e+00 1.1930000e+01 ... 8.3349000e+03
  1.1844000e+02 2.2385160e+03]
 [1.0959000e-01 0.0000000e+00 1.1930000e+01 ... 8.2624500e+03
  1.3608000e+02 2.5495560e+03]
 [4.7410000e-02 0.0000000e+00 1.1930000e+01 ... 8.3349000e+03
  1.6548000e+02 3.1275720e+03]]


CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX  ...       RAD_TAX  \
count  506.000000  506.000000  506.000000  506.000000  ...    506.000000   
mean    68.574901    3.795043    9.549407  408.237154  ...   5231.539526   
std     28.148861    2.105710    8.707259  168.537116  ...   6418.517581   
min      2.900000    1.129600    1.000000  187.000000  ...    198.000000   
25%     45.025000    2.100175    4.000000  279.000000  ...   1136.500000   
50%     77.500000    3.207450    5.000000  330.000000  ...   1790.000000   
75%     94.075000    5.188425   24.000000  666.000000  ...  15984.000000   
max    100.000000   12.126500   24.000000  711.000000  ...  15984.000000   

       RAD_PTRATIO       RAD_B   RAD_LSTAT   TAX_PTRATIO         TAX_B  \
count   506.000000   506.00000  506.000000    506.000000     506.00000   
mean    184.982806  3053.44749  151.154644   7702.055336  138823.11502   
std     180.171923  2960.05577  196.562582   3732.003358   64619.91997   
min      13.600000     7.68000    3.160000   2692.800000     213.12000   
25%      73.500000  1483.70250   30.050000   4913.600000  101240.04000   
50%      84.800000  1933.35000   57.630000   5924.100000  119658.91500   
75%     484.800000  2778.30000  171.480000  13453.200000  160982.30250   
max     484.800000  9525.60000  911.280000  14291.100000  282195.90000   

          TAX_LSTAT    PTRATIO_B  PTRATIO_LSTAT       B_LSTAT  
count    506.000000   506.000000     506.000000    506.000000  
mean    5818.871146  6547.619334     239.290334   4274.823238  
std     5083.126041  1837.557901     145.807763   2613.501822  
min      498.960000     6.464000      25.431000      5.580800  
25%     2051.340000  6140.250000     122.942000   2355.214275  
50%     3724.380000  7078.025500     205.030000   3804.722600  
75%     8489.782500  7695.286500     334.360500   5640.628650  
max    25288.020000  8421.600000     766.994000  15070.293000  

[8 rows x 104 columns]

## Spliting the Data to Train and Test

In [10]:
from sklearn import model_selection
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(data,target,random_state = 0)
X2_train,X2_test,Y2_train,Y2_test = model_selection.train_test_split(X2,target,random_state = 0)

## Import LinearRegression for Training Algorithm

In [11]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()
alg2 = LinearRegression()

## Fit the Data in Algorithm

In [12]:
alg1.fit(X_train,Y_train)
alg2.fit(X2_train,Y2_train)

LinearRegression()

## Predict the Output

In [13]:
X_pred = alg1.predict(X_train)
Y_pred = alg1.predict(X_test)
X2_pred = alg2.predict(X2_train)
Y2_pred = alg2.predict(X2_test)
X_pred,Y_pred,X2_pred,Y2_pred

(array([13.54334096, 21.03611757, 35.25707372, 19.31180705, 12.9193462 ,
        13.83454251, 22.66868871, 14.2409856 , 31.24023391, 25.2746277 ,
        15.13346462, 24.27169368,  9.08842615, 14.82179159, 21.01155502,
        32.97485525, 27.96169238, 25.76241079, 15.56154982, 31.08187689,
        28.10293564, 13.79628381,  7.39293584, 28.48119204, 25.40996121,
         4.34170732, 28.48040075, 17.16788093, 29.49717483, 20.3114614 ,
        15.95499192, 17.81088079, 12.68905582,  8.44914207, 19.28629969,
        34.45678405, 32.9718556 , 23.57990095, 19.63359906, 22.95623269,
        26.85871334, 21.77624643, 16.93785832, 32.00415847, 10.62790654,
        19.32739398, 32.23307479, 18.75153571, 15.81064522, 18.67130015,
        14.4104764 , 24.58123176, 24.07953473, 16.49458446, 13.19945057,
        20.38069625, 24.75377888, 17.22571167, 24.97600846, 22.55118033,
        27.83912426, 35.9434255 , 16.45240418, 11.58522008, 34.68756396,
        31.00776222, 20.65966773, 39.55056576, 29.0

## Comparing Scores

In [14]:
def cod_score(Y_Test, Y_Pred):
    u = ((Y_Test - Y_Pred)**2).sum()
    v = ((Y_Test - Y_Test.mean())**2).sum()
    result = 1 - (u/v)
    return result
train_score = cod_score(Y_train,X_pred)
test_score = cod_score(Y_test,Y_pred)
print("Train: ",train_score)
print("Test: ",test_score)

train_score_2 = cod_score(Y2_train,X2_pred)
test_score_2 = cod_score(Y2_test,Y2_pred)
print("Train_2: ",train_score_2)
print("Test_2: ",test_score_2)

Train:  0.7697699488741149
Test:  0.6354638433202129
Train_2:  0.9520519609032727
Test_2:  0.6074721959808899
